import { createTrademark, updateTrademark, deleteTrademark, getTrademark, uploadImage, STAGES, STATUS_WORKFLOW, CITIES, VALID_TYPES } from "@/lib/api";
import type { TrademarkInput, TrademarkRecord } from "@/lib/api";
import { useEffect, useMemo, useRef, useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { format } from "date-fns";
import { useQueryClient, useQuery, useMutation } from "@tanstack/react-query";
import { useToast } from "@/hooks/use-toast";
import { X, Save, Trash2, UploadCloud, Eye, CheckCircle2 } from "lucide-react";

const CASE_TYPES = ["Trademark", "Copyright", "Design", "Patent", "Renewal", "Opposition", "Other"];
const schema = z.object({
  date:z.string().min(1,"Date is required"), type:z.string().min(1,"Type is required"), clientCode:z.string().min(1,"Client Code is required"),
  caseNumber:z.string().min(1,"Case Number is required"), appName:z.string().min(1,"Application Name is required"), tmCprNo:z.string().optional(), appClass:z.string().optional(),
  stage:z.string().min(1,"Status is required"), subStage:z.string().optional(), caseType:z.string().optional(), agent:z.string().optional(), city:z.string().min(1,"City is required"), notes:z.string().optional(), image:z.string().optional(),
});
type FormValues=z.infer<typeof schema>;

function Label({children,required}:{children:React.ReactNode;required?:boolean}){return <label className="block mb-1.5 font-mono text-[10px] font-bold uppercase tracking-widest text-[#6d6658]">{children}{required&&<span className="ml-0.5 text-[#CC0000]">*</span>}</label>}
function Input(props:React.InputHTMLAttributes<HTMLInputElement>){return <input {...props} className={`w-full h-10 px-3 bg-white border-2 border-[#0C0C0C] font-mono text-sm focus:outline-2 focus:outline-[#C94A00] ${props.className||""}`}/>}
function Select(props:React.SelectHTMLAttributes<HTMLSelectElement>){return <select {...props} className={`w-full h-10 px-3 bg-white border-2 border-[#0C0C0C] font-mono text-sm focus:outline-2 focus:outline-[#C94A00] ${props.className||""}`}/>}
function Head({children}:{children:React.ReactNode}){return <div className="flex items-center gap-2 mb-4"><div className="font-mono text-xs font-bold uppercase tracking-widest">{children}</div><div className="flex-1 h-0.5 bg-black/10"/></div>}

export function RecordModal({recordId,isNew:forceNew,onClose,onSaved}:{recordId?:string;isNew?:boolean;onClose:()=>void;onSaved?:()=>void}){
  const creating=forceNew||!recordId; const {toast}=useToast(); const qc=useQueryClient(); const inputRef=useRef<HTMLInputElement>(null);
  const [preview,setPreview]=useState(""); const [uploading,setUploading]=useState(false); const [progress,setProgress]=useState(0);
  const {data:record,isLoading}=useQuery<TrademarkRecord|null>({queryKey:["trademark",recordId],queryFn:()=>getTrademark(recordId!),enabled:!creating&&!!recordId,staleTime:30000});
  const form=useForm<FormValues>({resolver:zodResolver(schema),defaultValues:{date:format(new Date(),"yyyy-MM-dd"),type:"X",clientCode:"",caseNumber:"",appName:"",tmCprNo:"",appClass:"",stage:"STAGE 1",subStage:"",caseType:"Trademark",agent:"",city:"Islamabad",notes:"",image:""}});
  useEffect(()=>{if(!record||creating)return;form.reset({date:record.date?.slice(0,10)||format(new Date(),"yyyy-MM-dd"),type:record.type||"X",clientCode:record.clientCode||"",caseNumber:record.caseNumber||"",appName:record.appName||"",tmCprNo:record.tmCprNo||"",appClass:record.appClass||"",stage:record.stage||"STAGE 1",subStage:record.subStage||"",caseType:record.caseType||"Trademark",agent:record.agent||"",city:record.city||"Islamabad",notes:record.notes||"",image:record.imagePath||""});setPreview(record.image||"");},[record,creating,form]);
  const availableTypes=useMemo(()=>Array.from(new Set([...VALID_TYPES,...(record?.type?[record.type]:[])])),[record]);
  const createMutation=useMutation({mutationFn:(input:TrademarkInput)=>createTrademark(input)}); const updateMutation=useMutation({mutationFn:(input:TrademarkInput)=>updateTrademark(recordId!,input)}); const deleteMutation=useMutation({mutationFn:()=>deleteTrademark(recordId!)});
  const upload=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;try{setUploading(true);const r=await uploadImage(file,p=>setProgress(p));form.setValue("image",r.fileId);setPreview(r.thumbnailUrl);toast({title:"Image uploaded",description:"Saved to private trademark storage."});}catch(e:any){toast({title:"Upload failed",description:e?.message||"Could not upload image",variant:"destructive"});}finally{setUploading(false);setProgress(0);if(inputRef.current)inputRef.current.value="";}};
  const submit=async(data:FormValues)=>{try{const payload:TrademarkInput={date:data.date,type:data.type,clientCode:data.clientCode,clientName:record?.clientName||undefined,caseNumber:data.caseNumber,appName:data.appName,tmCprNo:data.tmCprNo||undefined,appClass:data.appClass||undefined,stage:data.stage,subStage:data.subStage||undefined,caseType:data.caseType||undefined,agent:data.agent||undefined,city:data.city,notes:data.notes||undefined,image:data.image||undefined};if(creating)await createMutation.mutateAsync(payload);else await updateMutation.mutateAsync(payload);qc.invalidateQueries({queryKey:["trademarks"]});qc.invalidateQueries({queryKey:["trademark",recordId]});qc.invalidateQueries({queryKey:["record",recordId]});toast({title:creating?"✓ Record created":"✓ Record updated",description:"Basic case record saved."});onSaved?.();onClose();}catch(e:any){toast({title:"Save failed",description:e?.message||"Unable to save record",variant:"destructive"});}};
  const remove=()=>{if(!confirm("Delete this record permanently?"))return;deleteMutation.mutate(undefined,{onSuccess:()=>{toast({title:"Record deleted"});onClose()},onError:(e:any)=>toast({title:"Delete failed",description:e?.message||"Unable to delete",variant:"destructive"})})};
  const pending=createMutation.isPending||updateMutation.isPending||deleteMutation.isPending;
  const sub=STATUS_WORKFLOW[form.watch("stage")]||[];
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4"><div className="relative flex max-h-[92vh] w-full max-w-4xl flex-col overflow-hidden border-2 border-black bg-[#F0E8D0] shadow-[8px_8px_0_#0C0C0C]">
    <div className="flex shrink-0 items-center justify-between bg-[#0C0C0C] px-6 py-4 text-[#F0E8D0]"><div><div className="font-serif text-2xl uppercase tracking-widest">{creating?"ADD RECORD":"EDIT RECORD"}</div>{!creating&&record&&<div className="mt-1 font-mono text-[10px] uppercase tracking-widest text-[#C5B89A]">{record.prefix} · {record.clientCode} · {record.caseNumber}</div>}</div><button onClick={onClose} disabled={pending}><X className="h-6 w-6"/></button></div>
    {!creating&&isLoading?<div className="flex flex-1 items-center justify-center p-12 font-mono animate-pulse">LOADING RECORD…</div>:<form onSubmit={form.handleSubmit(submit)} className="flex min-h-0 flex-1 flex-col"><div className="min-h-0 flex-1 overflow-y-auto p-6 space-y-7">
      <section><Head>Basic Information</Head><div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-4"><div><Label required>DATE</Label><Input type="date" {...form.register("date")}/></div><div><Label required>TYPE / PREFIX</Label><Select {...form.register("type")}>{availableTypes.map(x=><option key={x}>{x}</option>)}</Select></div><div><Label required>CLIENT CODE</Label><Input placeholder="e.g. 284" {...form.register("clientCode")}/></div><div><Label required>CASE NUMBER</Label><Input placeholder="e.g. 001" {...form.register("caseNumber")}/></div><div className="sm:col-span-2 md:col-span-4"><Label required>APPLICATION / MARK NAME</Label><Input placeholder="Trademark / Application name" {...form.register("appName")}/></div></div></section>
      <section><Head>Case Information</Head><div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3"><div><Label required>STATUS</Label><Select {...form.register("stage")} onChange={e=>{form.setValue("stage",e.target.value);if(!(STATUS_WORKFLOW[e.target.value]||[]).includes(form.getValues("subStage")))form.setValue("subStage","")}}>{STAGES.map(x=><option key={x}>{x}</option>)}</Select></div><div className="md:col-span-2"><Label>SUB-STATUS</Label><Select value={form.watch("subStage")||""} onChange={e=>form.setValue("subStage",e.target.value)}><option value="">SELECT SUB-STATUS</option>{sub.map(x=><option key={x}>{x}</option>)}</Select></div><div><Label>TM / CPR NUMBER</Label><Input placeholder="e.g. 633710" {...form.register("tmCprNo")}/></div><div><Label>CLASS</Label><Select {...form.register("appClass")}><option value="">SELECT</option>{Array.from({length:45},(_,i)=>String(i+1)).map(x=><option key={x}>{x}</option>)}</Select></div><div><Label>CASE TYPE</Label><Select {...form.register("caseType")}>{CASE_TYPES.map(x=><option key={x}>{x}</option>)}</Select></div></div></section>
      <section><Head>Assignment</Head><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><div><Label required>CITY</Label><Select {...form.register("city")}>{CITIES.map(x=><option key={x}>{x}</option>)}</Select></div><div><Label>AGENT</Label><Input placeholder="Agent name" {...form.register("agent")}/></div></div></section>
      <section><Head>Notes</Head><textarea {...form.register("notes")} rows={3} placeholder="Internal notes…" className="w-full resize-none border-2 border-black bg-white p-3 font-mono text-sm"/></section>
      <section><Head>Trademark Image</Head><input ref={inputRef} type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={upload}/><div className="flex flex-wrap items-center gap-3 border-2 border-black bg-white p-4"><button type="button" onClick={()=>inputRef.current?.click()} disabled={uploading} className="flex h-10 items-center gap-2 bg-[#0C0C0C] px-4 font-mono text-xs font-bold text-[#F0E8D0]"><UploadCloud className="h-4 w-4"/>{uploading?`UPLOADING ${progress}%`:form.watch("image")?"REPLACE IMAGE":"UPLOAD IMAGE"}</button>{form.watch("image")&&<><button type="button" onClick={()=>{form.setValue("image","");setPreview("")}} className="h-10 border-2 border-[#CC0000] px-3 font-mono text-xs font-bold text-[#CC0000]">REMOVE</button><button type="button" onClick={()=>setPreview(preview||form.watch("image")||"")} className="flex items-center gap-1 font-mono text-xs font-bold text-[#C94A00]"><Eye className="h-4 w-4"/> PREVIEW</button><CheckCircle2 className="h-4 w-4 text-[#0A6B52]"/></>}</div></section>
      <div className="border-2 border-[#0A6B52]/40 bg-[#E7F2ED] p-4"><div className="font-mono text-xs font-black uppercase tracking-widest">RELATED SHEETS</div><p className="mt-1 font-mono text-[10px] leading-relaxed text-[#3f554c]">TM5, TM6, TM11, TM16, TM56, JOURNAL and GENERAL are maintained as separate sheet-style entries matched by TM / CPR number. Add or edit those entries from the related sheets so the case automatically picks up matching records.</p></div>
    </div><div className="flex shrink-0 items-center justify-between border-t-2 border-black bg-[#E8DFC7] px-6 py-4">{!creating?<button type="button" onClick={remove} disabled={pending} className="flex h-10 items-center gap-2 border-2 border-[#CC0000] bg-white px-4 font-mono text-xs font-bold text-[#CC0000]"><Trash2 className="h-4 w-4"/> DELETE</button>:<div/>}<div className="flex gap-3"><button type="button" onClick={onClose} disabled={pending} className="h-10 border-2 border-black bg-white px-5 font-mono text-xs font-bold">CANCEL</button><button type="submit" disabled={pending} className="flex h-10 items-center gap-2 bg-[#C94A00] px-6 font-mono text-xs font-bold text-white"><Save className="h-4 w-4"/>{pending?"SAVING…":creating?"SAVE RECORD":"UPDATE RECORD"}</button></div></div></form>}
  </div></div>;
}
