import { listTrademarks } from "@/lib/api";
import type { TrademarkRecord } from "@/lib/api";
import { supabase } from "@/lib/supabase";
import { AppShell } from "@/components/layout/AppShell";
import { formatDateShort } from "@/lib/utils";
import { useMemo, useState } from "react";
import { useLocation } from "wouter";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, Clock3, Filter, Flag, Search, UserCheck, UserX, Users2, X } from "lucide-react";

const CONDITIONS=["NORMAL","COMPROMISED","PROLONGED","COURT / HEARING"];
const STAGE_BADGE:Record<string,string>={"STAGE 1":"bg-[#0D9970] text-white","STAGE 2":"bg-[#D4A800] text-black","STAGE 3":"bg-[#C94A00] text-white","STAGE 4":"bg-[#0A6B52] text-white",STOPPED:"bg-[#CC0000] text-white"};
type Assignment={id:string;trademark_id:string|null;agent_name:string|null;assigned_at:string|null;response_status:string|null;responded_at:string|null;notes:string|null};
function Select({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(v:string)=>void}){return <div className="flex flex-col gap-1"><label className="font-mono text-[9px] font-bold uppercase tracking-widest text-[#6d6658]">{label}</label><select value={value} onChange={e=>onChange(e.target.value)} className="h-9 min-w-[130px] border-2 border-black bg-white px-2 font-mono text-xs"><option value="">ALL</option>{options.map(x=><option key={x}>{x}</option>)}</select></div>}
function Metric({label,value,icon:Icon}:{label:string;value:number;icon:any}){return <div className="border-2 border-black bg-white p-3 shadow-[3px_3px_0_#0C0C0C]"><div className="flex items-center gap-2 text-[#6d6658]"><Icon className="h-4 w-4"/><span className="font-mono text-[9px] font-bold uppercase tracking-widest">{label}</span></div><div className="mt-1 font-serif text-3xl font-bold">{value}</div></div>}
export function AssignedPage(){const [,navigate]=useLocation();const qc=useQueryClient();const [agent,setAgent]=useState("");const [stage,setStage]=useState("");const [subStage,setSubStage]=useState("");const [condition,setCondition]=useState("");const [from,setFrom]=useState("");const [to,setTo]=useState("");const [q,setQ]=useState("");const [show,setShow]=useState(true);
 const {data:records=[],isLoading}=useQuery<TrademarkRecord[]>({queryKey:["trademarks"],queryFn:()=>listTrademarks(),staleTime:15000});
 const {data:assignments=[],isLoading:assignLoading}=useQuery<Assignment[]>({queryKey:["agent-assignments"],queryFn:async()=>{const {data,error}=await supabase.from("agent_assignments").select("id,trademark_id,agent_name,assigned_at,response_status,responded_at,notes").order("assigned_at",{ascending:false});if(error)throw error;return (data??[]) as Assignment[]},staleTime:10000});
 const activeAssignments=useMemo(()=>{const m=new Map<string,Assignment>();for(const a of assignments){if(!a.trademark_id)continue;if(a.response_status!=="REJECTED"&&a.response_status!=="COMPLETED"&&!m.has(a.trademark_id))m.set(a.trademark_id,a)}return m},[assignments]);
 const allByTm=useMemo(()=>{const m=new Map<string,Assignment>();for(const a of assignments)if(a.trademark_id&&!m.has(a.trademark_id))m.set(a.trademark_id,a);return m},[assignments]);
 const distinct=useMemo(()=>({agents:[...new Set(records.map(r=>r.agent).filter(Boolean) as string[])].sort(),stages:[...new Set(records.map(r=>r.stage).filter(Boolean) as string[])].sort(),subStages:[...new Set(records.map(r=>r.subStage).filter(Boolean) as string[])].sort()}),[records]);
 const filtered=useMemo(()=>{const needle=q.trim().toLowerCase();return records.filter(r=>{const a=activeAssignments.get(r.id);if(!a)return false;if(agent&&r.agent!==agent)return false;if(stage&&r.stage!==stage)return false;if(subStage&&r.subStage!==subStage)return false;if(condition&&(r.condition||"NORMAL")!==condition)return false;if(from&&String(r.date||"")<from)return false;if(to&&String(r.date||"")>to)return false;if(needle&&!([r.prefix,r.clientCode,r.caseNumber,r.appName,r.tmCprNo,r.agent].some(v=>String(v??"").toLowerCase().includes(needle))))return false;return true}).sort((a,b)=>new Date(b.updatedAt||b.date||0).getTime()-new Date(a.updatedAt||a.date||0).getTime())},[records,activeAssignments,agent,stage,subStage,condition,from,to,q]);
 const metrics=useMemo(()=>{let accepted=0,pending=0,rejected=0,completed=0;for(const a of assignments){if(a.response_status==="ACCEPTED")accepted++;else if(a.response_status==="PENDING")pending++;else if(a.response_status==="REJECTED")rejected++;else if(a.response_status==="COMPLETED")completed++}return {assigned:activeAssignments.size,accepted,rejected,completed,pending}},[assignments,activeAssignments]);
 const setAssignment=useMutation({mutationFn:async({a,r,status}:{a:Assignment;r:TrademarkRecord;status:string})=>{const payload={trademark_id:r.id,agent_name:r.agent||a.agent_name||null,response_status:status,responded_at:status==="PENDING"?null:new Date().toISOString()};const {error}=await supabase.from("agent_assignments").update(payload).eq("id",a.id);if(error)throw error},onSuccess:()=>{qc.invalidateQueries({queryKey:["agent-assignments"]});qc.invalidateQueries({queryKey:["trademarks"]})}});
 const flag=useMutation({mutationFn:async({id,value}:{id:string;value:string})=>{const {error}=await supabase.from("trademarks").update({condition:value}).eq("id",id);if(error)throw error},onSuccess:()=>qc.invalidateQueries({queryKey:["trademarks"]})});
 const clear=()=>{setAgent("");setStage("");setSubStage("");setCondition("");setFrom("");setTo("");setQ("")};
 return <AppShell><div className="flex h-full min-h-0 flex-col bg-white"><div className="shrink-0 border-b-2 border-black bg-[#E8DFC7] px-5 py-4"><div className="flex flex-wrap items-center gap-3"><Users2 className="h-5 w-5 text-[#0A6B52]"/><h1 className="font-serif text-2xl uppercase tracking-widest">AGENT CONTROL</h1><span className="ml-auto font-mono text-[10px] font-bold uppercase tracking-widest text-[#6d6658]">{isLoading||assignLoading?"LOADING…":`${filtered.length} ACTIVE ASSIGNMENTS`}</span><button onClick={()=>setShow(v=>!v)} className="flex h-9 items-center gap-2 border-2 border-black bg-white px-3 font-mono text-[10px] font-bold"><Filter className="h-4 w-4"/> FILTERS</button></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-5"><Metric label="Assigned" value={metrics.assigned} icon={Users2}/><Metric label="Accepted" value={metrics.accepted} icon={UserCheck}/><Metric label="Rejected" value={metrics.rejected} icon={UserX}/><Metric label="Completed" value={metrics.completed} icon={CheckCircle2}/><Metric label="Pending" value={metrics.pending} icon={Clock3}/></div>{show&&<div className="mt-4 flex flex-wrap items-end gap-3 border-t border-black/20 pt-3"><div><label className="font-mono text-[9px] font-bold uppercase text-[#6d6658]">SEARCH</label><div className="relative mt-1"><Search className="absolute left-2 top-2 h-4 w-4 text-[#6d6658]"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Case / mark / TM…" className="h-9 w-[220px] border-2 border-black bg-white pl-8 pr-2 font-mono text-xs"/></div></div><Select label="AGENT" value={agent} options={distinct.agents} onChange={setAgent}/><Select label="STAGE" value={stage} options={distinct.stages} onChange={setStage}/><Select label="SUB-STAGE" value={subStage} options={distinct.subStages} onChange={setSubStage}/><Select label="CONDITION" value={condition} options={CONDITIONS} onChange={setCondition}/><div><label className="font-mono text-[9px] font-bold uppercase text-[#6d6658]">FROM</label><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="mt-1 h-9 border-2 border-black bg-white px-2 font-mono text-xs"/></div><div><label className="font-mono text-[9px] font-bold uppercase text-[#6d6658]">TO</label><input type="date" value={to} onChange={e=>setTo(e.target.value)} className="mt-1 h-9 border-2 border-black bg-white px-2 font-mono text-xs"/></div><button onClick={clear} className="flex h-9 items-center gap-1 border-2 border-[#CC0000] px-3 font-mono text-[10px] font-bold text-[#CC0000]"><X className="h-3 w-3"/> CLEAR</button></div>}</div>
 <div className="min-h-0 flex-1 overflow-auto"><table className="w-full border-collapse whitespace-nowrap font-mono text-xs"><thead className="sticky top-0 z-10 bg-black text-[#F0E8D0]"><tr>{["CASE","MARK / APPLICATION","TM / CPR","STAGE","SUB-STAGE","AGENT","ASSIGNMENT","DATE","FLAG"].map(h=><th key={h} className="px-3 py-3 text-left text-[9px]">{h}</th>)}</tr></thead><tbody>{filtered.length===0?<tr><td colSpan={9} className="p-12 text-center text-[#6d6658]">NO ACTIVE ASSIGNMENTS. REJECTED AND COMPLETED CASES ARE HIDDEN.</td></tr>:filtered.map((r,i)=>{const a=activeAssignments.get(r.id)!;const status=a.response_status||"PENDING";const c=r.condition||"NORMAL";const flagged=c!=="NORMAL"||r.isProlonged;return <tr key={r.id} className={`border-b border-black/10 ${flagged?"bg-red-50":i%2?"bg-white":"bg-[#F0E8D0]"}`}><td className="px-3 py-2 font-bold text-[#0A6B52]">{r.prefix} · {r.clientCode} · {r.caseNumber}</td><td className="max-w-[250px] truncate px-3 py-2 font-semibold">{r.appName||"—"}</td><td className="px-3 py-2 font-bold">{r.tmCprNo||"—"}</td><td className="px-3 py-2"><span className={`inline-block px-2 py-1 text-[9px] font-bold ${STAGE_BADGE[r.stage]||"bg-black text-white"}`}>{r.stage}</span></td><td className="max-w-[190px] truncate px-3 py-2">{r.subStage||"—"}</td><td className="px-3 py-2 font-bold">{r.agent||a.agent_name||"—"}</td><td className="px-3 py-2" onClick={e=>e.stopPropagation()}><div className="flex gap-1"><button disabled={setAssignment.isPending} onClick={()=>setAssignment.mutate({a,r,status:"ACCEPTED"})} className={`border-2 px-2 py-1 text-[9px] font-bold ${status==="ACCEPTED"?"border-[#0A6B52] bg-[#0A6B52] text-white":"border-black bg-white"}`}>ACCEPT</button><button disabled={setAssignment.isPending} onClick={()=>setAssignment.mutate({a,r,status:"REJECTED"})} className="border-2 border-[#CC0000] bg-white px-2 py-1 text-[9px] font-bold text-[#CC0000]">REJECT</button><button disabled={setAssignment.isPending} onClick={()=>setAssignment.mutate({a,r,status:"COMPLETED"})} className="border-2 border-[#0A6B52] bg-white px-2 py-1 text-[9px] font-bold text-[#0A6B52]">COMPLETE</button></div></td><td className="px-3 py-2 text-[#6d6658]">{formatDateShort(r.date)}</td><td className="px-3 py-2"><button onClick={()=>flag.mutate({id:r.id,value:c==="NORMAL"?"COMPROMISED":"NORMAL"})} className={`inline-flex items-center gap-1 border-2 px-2 py-1 text-[9px] font-bold ${flagged?"border-[#CC0000] bg-red-100 text-[#CC0000]":"border-black bg-white"}`}><Flag className="h-3 w-3"/>{flagged?"UNFLAG":"FLAG"}</button></td></tr>})}</tbody></table></div></div></AppShell>}
