import { AppShell } from "@/components/layout/AppShell";
import { supabase } from "@/lib/supabase";
import { uploadImage } from "@/lib/api";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useRef, useState } from "react";
import { addMonths, format } from "date-fns";
import { BookOpen, FilePlus2, ImagePlus, Trash2, X } from "lucide-react";

const TABS=["TM5","TM6","TM11","TM16","TM56","JOURNAL","GENERAL"] as const;
type FormCode=typeof TABS[number];
type Entry=Record<string,any> & {id:string;form_code:FormCode;tm_cpr_number:string;form_number:string|null;form_date:string|null;due_date:string|null;target_tm_number:string|null;application_name:string|null;nice_class:string|null;applicant_name:string|null;agent_name:string|null;filing_date:string|null;notes:string|null;image_path:string|null};

function Input({className="",...p}:React.InputHTMLAttributes<HTMLInputElement>){return <input {...p} className={`h-9 w-full border-2 border-black bg-white px-2 font-mono text-xs ${className}`}/>}
function Label({children}:{children:React.ReactNode}){return <label className="block font-mono text-[9px] font-bold uppercase tracking-widest text-[#6d6658]">{children}</label>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div><Label>{label}</Label><div className="mt-1">{children}</div></div>}
function dueDate(date:string,months:number){return date?format(addMonths(new Date(`${date}T00:00:00`),months),"yyyy-MM-dd"):""}

const META:Record<FormCode,{title:string;hint:string}>={
 TM5:{title:"TM5 · OPPOSITION FILED",hint:"Against another trademark. Match by the target TM number."},
 TM6:{title:"TM6 · COUNTER-STATEMENT / REPLY",hint:"Reply to an opposition. Due date is calculated automatically from the received/filing date."},
 TM11:{title:"TM11 · DEMAND NOTE",hint:"Registration fee / demand note stage. Only submission date is required."},
 TM16:{title:"TM16 · CORRECTION IN APPLICATION",hint:"Only submission date is required."},
 TM56:{title:"TM56 · CORRESPONDENCE ADDRESS CHANGE",hint:"Only submission date is required."},
 JOURNAL:{title:"JOURNAL · MONTHLY PUBLICATION",hint:"Match by TM / CPR. Opposition deadline is calculated as publication date + 2 months."},
 GENERAL:{title:"GENERAL · DISPLAY RECORD",hint:"A simple sheet for general IPO entries, matched by TM / CPR number."},
};

export function FormsPage(){
 const qc=useQueryClient(); const [tab,setTab]=useState<FormCode>("TM5"); const [open,setOpen]=useState(false); const [edit,setEdit]=useState<Entry|null>(null);
 const [p,setP]=useState<any>({}); const [uploading,setUploading]=useState(false); const fileRef=useRef<HTMLInputElement>(null);
 const {data:entries=[],isLoading,error}=useQuery<Entry[]>({queryKey:["related-forms",tab],queryFn:async()=>{const {data,error}=await supabase.from("related_form_entries").select("*").eq("form_code",tab).order("form_date",{ascending:false}).limit(5000);if(error)throw error;return (data??[]) as Entry[]},staleTime:15000});
 const save=useMutation({mutationFn:async()=>{const clean=(v:any)=>v===""?null:v; const {data:auth}=await supabase.auth.getUser(); const payload:any={form_code:tab,tm_cpr_number:String(p.tm_cpr_number||"").trim(),form_number:clean(p.form_number),form_date:clean(p.form_date),due_date:clean(p.due_date),target_tm_number:clean(p.target_tm_number),application_name:clean(p.application_name),nice_class:clean(p.nice_class),applicant_name:clean(p.applicant_name),agent_name:clean(p.agent_name),filing_date:clean(p.filing_date),notes:clean(p.notes),image_path:clean(p.image_path),updated_by:auth.user?.id};if(!payload.tm_cpr_number)throw new Error("TM / CPR number is required.");if(edit){const {error}=await supabase.from("related_form_entries").update(payload).eq("id",edit.id);if(error)throw error;}else{payload.created_by=auth.user?.id;const {error}=await supabase.from("related_form_entries").insert(payload);if(error)throw error;}} ,onSuccess:()=>{qc.invalidateQueries({queryKey:["related-forms",tab]});setOpen(false);setEdit(null);setP({});}});
 const remove=useMutation({mutationFn:async(id:string)=>{const {error}=await supabase.from("related_form_entries").delete().eq("id",id);if(error)throw error},onSuccess:()=>qc.invalidateQueries({queryKey:["related-forms",tab]})});
 const set=(k:string,v:any)=>setP((x:any)=>({...x,[k]:v}));
 const start=(e?:Entry)=>{setEdit(e||null);setP(e?{...e}:{form_date:format(new Date(),"yyyy-MM-dd")});setOpen(true)};
 const filtered=useMemo(()=>entries,[entries]);
 return <AppShell><div className="flex h-full min-h-0 flex-col bg-[#F0E8D0] p-4 sm:p-5"><div className="mx-auto flex w-full max-w-7xl min-h-0 flex-1 flex-col gap-4">
   <header className="flex flex-wrap items-center gap-3 border-b-2 border-black pb-4"><FilePlus2 className="h-6 w-6"/><div><h1 className="font-serif text-3xl uppercase tracking-widest">RELATED SHEETS</h1><p className="font-mono text-[9px] font-bold uppercase tracking-wider text-[#6d6658]">Enter a form here once · exact TM / CPR matching links it to the case automatically.</p></div><button onClick={()=>start()} className="ml-auto flex h-10 items-center gap-2 bg-[#C94A00] px-4 font-mono text-xs font-bold text-white"><FilePlus2 className="h-4 w-4"/> ADD {tab}</button></header>
   <div className="flex gap-1 overflow-x-auto border-b-2 border-black">{TABS.map(t=><button key={t} onClick={()=>{setTab(t);setOpen(false)}} className={`shrink-0 border-2 border-b-0 px-4 py-2 font-mono text-[10px] font-black ${tab===t?"bg-black text-[#F0E8D0]":"bg-white"}`}>{t}</button>)}</div>
   <div className="border-2 border-black bg-white p-4"><div className="font-mono text-sm font-black uppercase">{META[tab].title}</div><div className="mt-1 font-mono text-[10px] text-[#6d6658]">{META[tab].hint}</div></div>
   <div className="min-h-0 flex-1 overflow-auto border-2 border-black bg-white"><table className="w-full whitespace-nowrap font-mono text-xs"><thead className="sticky top-0 bg-black text-[#F0E8D0]"><tr>{["TM / CPR","FORM / JOURNAL NO","DATE","DUE","TARGET TM","APPLICATION / MARK","CLASS","APPLICANT","AGENT","ACTION"].map(h=><th key={h} className="px-3 py-3 text-left text-[9px]">{h}</th>)}</tr></thead><tbody>{isLoading?<tr><td colSpan={10} className="p-10 text-center">LOADING…</td></tr>:error?<tr><td colSpan={10} className="p-10 text-center text-red-800">FAILED TO LOAD {tab}</td></tr>:filtered.length===0?<tr><td colSpan={10} className="p-10 text-center text-[#6d6658]">NO {tab} ENTRIES. ADD ONE ABOVE.</td></tr>:filtered.map(e=><tr key={e.id} className="border-b border-black/10 odd:bg-[#F0E8D0]"><td className="px-3 py-2 font-bold">{e.tm_cpr_number}</td><td className="px-3 py-2">{e.form_number||"—"}</td><td className="px-3 py-2">{e.form_date||"—"}</td><td className="px-3 py-2 font-bold">{e.due_date||"—"}</td><td className="px-3 py-2">{e.target_tm_number||"—"}</td><td className="max-w-[220px] truncate px-3 py-2">{e.application_name||"—"}</td><td className="px-3 py-2">{e.nice_class||"—"}</td><td className="max-w-[220px] truncate px-3 py-2">{e.applicant_name||"—"}</td><td className="px-3 py-2">{e.agent_name||"—"}</td><td className="px-3 py-2"><div className="flex gap-2"><button onClick={()=>start(e)} className="border-2 border-black px-2 py-1 text-[9px] font-bold">EDIT</button><button onClick={()=>remove.mutate(e.id)} className="border-2 border-[#CC0000] px-2 py-1 text-[9px] font-bold text-[#CC0000]"><Trash2 className="h-3 w-3"/></button></div></td></tr>)}</tbody></table></div>
   {open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4"><div className="flex max-h-[92vh] w-full max-w-3xl flex-col overflow-hidden border-2 border-black bg-[#F0E8D0] shadow-[8px_8px_0_#0C0C0C]"><div className="flex items-center justify-between bg-black px-5 py-4 text-[#F0E8D0]"><div className="font-serif text-2xl uppercase tracking-widest">{edit?"EDIT":"ADD"} {tab}</div><button onClick={()=>setOpen(false)}><X/></button></div><div className="flex-1 overflow-y-auto p-5"><div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
     <Field label="TM / CPR NUMBER"><Input value={p.tm_cpr_number||""} onChange={e=>set("tm_cpr_number",e.target.value)} placeholder="Exact TM / CPR — matching key"/></Field>
     {(tab==="TM5")&&<><Field label="AGAINST TRADEMARK NUMBER"><Input value={p.target_tm_number||""} onChange={e=>set("target_tm_number",e.target.value)}/></Field><Field label="OPPOSITION FILED DATE"><Input type="date" value={p.form_date||""} onChange={e=>set("form_date",e.target.value)}/></Field><Field label="OPPOSITION NUMBER"><Input value={p.form_number||""} onChange={e=>set("form_number",e.target.value)}/></Field></>}
     {(tab==="TM6")&&<><Field label="OPPOSITION NUMBER"><Input value={p.form_number||""} onChange={e=>set("form_number",e.target.value)}/></Field><Field label="OPPOSITION RECEIVED / FILING DATE"><Input type="date" value={p.form_date||""} onChange={e=>{set("form_date",e.target.value);set("due_date",dueDate(e.target.value,1))}}/></Field><Field label="REPLY DUE (+1 MONTH)"><Input type="date" value={p.due_date||dueDate(p.form_date||"",1)} onChange={e=>set("due_date",e.target.value)}/></Field></>}
     {(tab==="TM11"||tab==="TM16"||tab==="TM56")&&<Field label="SUBMISSION DATE"><Input type="date" value={p.form_date||""} onChange={e=>set("form_date",e.target.value)}/></Field>}
     {(tab==="JOURNAL")&&<><Field label="JOURNAL NUMBER"><Input value={p.form_number||""} onChange={e=>set("form_number",e.target.value)}/></Field><Field label="PUBLICATION DATE"><Input type="date" value={p.form_date||""} onChange={e=>{set("form_date",e.target.value);set("due_date",dueDate(e.target.value,2))}}/></Field><Field label="OPPOSITION DEADLINE (+2 MONTHS)"><Input type="date" value={p.due_date||dueDate(p.form_date||"",2)} onChange={e=>set("due_date",e.target.value)}/></Field><Field label="APPLICATION / MARK"><Input value={p.application_name||""} onChange={e=>set("application_name",e.target.value)}/></Field><Field label="CLASS"><Input value={p.nice_class||""} onChange={e=>set("nice_class",e.target.value)}/></Field><Field label="FILING DATE"><Input type="date" value={p.filing_date||""} onChange={e=>set("filing_date",e.target.value)}/></Field></>}
     {(tab==="GENERAL")&&<><Field label="GENERAL NUMBER"><Input value={p.form_number||""} onChange={e=>set("form_number",e.target.value)}/></Field><Field label="DATE"><Input type="date" value={p.form_date||""} onChange={e=>set("form_date",e.target.value)}/></Field><Field label="APPLICATION NAME"><Input value={p.application_name||""} onChange={e=>set("application_name",e.target.value)}/></Field><Field label="TM / CPR NUMBER"><Input value={p.tm_cpr_number||""} onChange={e=>set("tm_cpr_number",e.target.value)}/></Field><Field label="CLASS"><Input value={p.nice_class||""} onChange={e=>set("nice_class",e.target.value)}/></Field><Field label="APPLICANT NAME"><Input value={p.applicant_name||""} onChange={e=>set("applicant_name",e.target.value)}/></Field><Field label="AGENT NAME"><Input value={p.agent_name||""} onChange={e=>set("agent_name",e.target.value)}/></Field><Field label="DATE OF FILING"><Input type="date" value={p.filing_date||""} onChange={e=>set("filing_date",e.target.value)}/></Field></>}
   </div><div className="mt-4"><Field label="NOTES"><textarea value={p.notes||""} onChange={e=>set("notes",e.target.value)} rows={2} className="w-full border-2 border-black bg-white p-2 font-mono text-xs"/></Field></div>
   {tab==="GENERAL"&&<div className="mt-4"><Label>IMAGE (OPTIONAL)</Label><input ref={fileRef} type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{setUploading(true);const r=await uploadImage(f);set("image_path",r.fileId)}finally{setUploading(false)}}}/><button type="button" disabled={uploading} onClick={()=>fileRef.current?.click()} className="mt-1 flex h-9 items-center gap-2 border-2 border-black bg-white px-3 font-mono text-xs"><ImagePlus className="h-4 w-4"/>{uploading?"UPLOADING…":p.image_path?"IMAGE ATTACHED":"ADD IMAGE"}</button></div>}
   </div><div className="flex justify-end gap-3 border-t-2 border-black bg-[#E8DFC7] px-5 py-4"><button onClick={()=>setOpen(false)} className="h-10 border-2 border-black bg-white px-5 font-mono text-xs font-bold">CANCEL</button><button disabled={save.isPending} onClick={()=>save.mutate()} className="h-10 bg-[#C94A00] px-6 font-mono text-xs font-bold text-white">{save.isPending?"SAVING…":"SAVE ENTRY"}</button></div></div></div>}
 </div></div>;
}
