import { AppShell } from "@/components/layout/AppShell";
import { supabase } from "@/lib/supabase";
import { useQuery } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { Link } from "wouter";
import { Search, BookOpen, Plus } from "lucide-react";

type JournalRow={id:string;form_number:string|null;form_date:string|null;due_date:string|null;tm_cpr_number:string;application_name:string|null;nice_class:string|null;applicant_name:string|null;filing_date:string|null};

export function JournalPage(){
 const [query,setQuery]=useState("");const [month,setMonth]=useState("");
 const {data=[],isLoading,error}=useQuery<JournalRow[]>({queryKey:["journal-publications"],queryFn:async()=>{
   const primary=await supabase.from("related_form_entries").select("id,form_number,form_date,due_date,tm_cpr_number,application_name,nice_class,applicant_name,filing_date").eq("form_code","JOURNAL").order("form_date",{ascending:false}).limit(5000);
   if(!primary.error)return (primary.data??[]) as JournalRow[];
   const fallback=await supabase.from("journal_publications").select("id,journal_no,publication_date,trademark_number,title,class,filing_date").order("publication_date",{ascending:false}).limit(5000);
   if(fallback.error)throw new Error(`Journal load failed: ${primary.error.message}; fallback: ${fallback.error.message}`);
   return (fallback.data??[]).map((r:any)=>({id:r.id,form_number:r.journal_no,form_date:r.publication_date,due_date:null,tm_cpr_number:r.trademark_number||"",application_name:r.title,nice_class:r.class,applicant_name:null,filing_date:r.filing_date})) as JournalRow[];
 },staleTime:15000,retry:1});
 const months=useMemo(()=>[...new Set(data.map(r=>String(r.form_date??"").slice(0,7)).filter(Boolean))].sort().reverse(),[data]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return data.filter(r=>(!month||String(r.form_date??"").startsWith(month))&&(!q||[r.form_number,r.tm_cpr_number,r.application_name,r.nice_class,r.applicant_name].some(v=>String(v??"").toLowerCase().includes(q))))},[data,month,query]);
 return <AppShell><div className="flex h-full min-h-0 flex-col bg-[#F0E8D0] p-5"><div className="mx-auto flex w-full max-w-7xl min-h-0 flex-1 flex-col gap-4"><header className="flex flex-wrap items-center gap-3 border-b-2 border-black pb-4"><BookOpen className="h-6 w-6"/><div><h1 className="font-serif text-3xl uppercase tracking-widest">JOURNAL</h1><p className="font-mono text-[9px] font-bold uppercase tracking-wider text-[#6d6658]">Monthly publication sheet · exact TM / CPR matching</p></div><span className="ml-auto font-mono text-xs font-bold">{filtered.length} ENTRIES</span><Link href="/forms" className="flex h-9 items-center gap-2 bg-[#C94A00] px-3 font-mono text-[10px] font-bold text-white"><Plus className="h-4 w-4"/> ADD / EDIT SHEET</Link></header><div className="flex flex-wrap gap-2"><div className="relative min-w-[260px] flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search TM, application, journal…" className="h-9 w-full border-2 border-black bg-white pl-9 pr-3 font-mono text-xs"/></div><select value={month} onChange={e=>setMonth(e.target.value)} className="h-9 border-2 border-black bg-white px-3 font-mono text-xs"><option value="">ALL MONTHS</option>{months.map(m=><option key={m}>{m}</option>)}</select></div><div className="min-h-0 flex-1 overflow-auto border-2 border-black bg-white"><table className="w-full whitespace-nowrap font-mono text-xs"><thead className="sticky top-0 bg-black text-[#F0E8D0]"><tr>{["JOURNAL NO","PUBLICATION DATE","OPPOSITION DEADLINE","TM / CPR","APPLICATION / MARK","CLASS","FILING DATE"].map(h=><th key={h} className="px-3 py-3 text-left text-[9px]">{h}</th>)}</tr></thead><tbody>{isLoading?<tr><td colSpan={7} className="p-10 text-center">LOADING JOURNAL…</td></tr>:error?<tr><td colSpan={7} className="p-10 text-center text-red-800">JOURNAL LOAD FAILED — {String((error as Error).message||"CHECK RELATED SHEETS")}</td></tr>:filtered.length===0?<tr><td colSpan={7} className="p-10 text-center text-[#6d6658]">NO JOURNAL ENTRIES</td></tr>:filtered.map(r=><tr key={r.id} className="border-b border-black/10 odd:bg-[#F0E8D0]"><td className="px-3 py-2 font-bold">{r.form_number||"—"}</td><td className="px-3 py-2">{r.form_date||"—"}</td><td className="px-3 py-2 font-bold">{r.due_date||"—"}</td><td className="px-3 py-2 font-bold">{r.tm_cpr_number||"—"}</td><td className="max-w-[300px] truncate px-3 py-2">{r.application_name||"—"}</td><td className="px-3 py-2">{r.nice_class||"—"}</td><td className="px-3 py-2">{r.filing_date||"—"}</td></tr>)}</tbody></table></div></div></div></AppShell>}
