import { getRecord } from "@/lib/api";
import type { TrademarkRecord } from "@/lib/api";
import { AppShell } from "@/components/layout/AppShell";
import { RecordModal } from "@/components/RecordModal";
import { RecordHistoryPanel } from "@/components/RecordHistoryPanel";
import { formatDate, formatDateShort } from "@/lib/utils";
import { supabase } from "@/lib/supabase";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { useLocation } from "wouter";
import { ArrowLeft, BookOpen, CheckCircle2, Edit2, ExternalLink, Image as ImageIcon, MinusCircle, Printer, Save, X } from "lucide-react";

interface Props { params: { id: string } }

const STATUS_COLOR: Record<string, string> = { "STAGE 1": "bg-emerald-700 text-white", "STAGE 2": "bg-amber-500 text-black", "STAGE 3": "bg-orange-700 text-white", "STAGE 4": "bg-teal-800 text-white", "STOPPED": "bg-red-800 text-white" };

const DOCS = [
  { key: "tm5", code: "TM5", title: "Filing Opposition", detail: "Opposition filed against someone / another trademark." },
  { key: "tm6", code: "TM6", title: "Counter-Statement", detail: "Reply/counter-statement when someone opposes our trademark." },
  { key: "tm11", code: "TM11", title: "Demand Note", detail: "Registration fee / demand note stage after the opposition period." },
  { key: "tm16", code: "TM16", title: "Correction in Application", detail: "Correction or amendment in the application." },
  { key: "tm56", code: "TM56", title: "Correspondence Address Change", detail: "Change of correspondence address." },
] as const;
type DocKey = typeof DOCS[number]["key"];

function Field({ label, value, wide = false }: { label: string; value?: string | null; wide?: boolean }) { return <div className={wide ? "sm:col-span-2" : ""}><div className="font-mono text-[8px] font-black uppercase tracking-widest text-[#3A506B]">{label}</div><div className="mt-1 min-h-[22px] border-b border-black/10 pb-1 font-mono text-xs font-bold break-words">{value || ""}</div></div>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="print-avoid-break"><div className="mb-3 flex items-center gap-3"><h2 className="font-mono text-[10px] font-black uppercase tracking-[0.16em] text-[#0A1931]">{title}</h2><div className="h-px flex-1 bg-black/15"/></div>{children}</section>; }
function TmChip({ name, active }: { name: string; active: boolean }) { return <div className={`flex items-center gap-1.5 border-2 px-3 py-2 font-mono text-[9px] font-black ${active ? "border-[#0A6B52] bg-[#0A6B52] text-white" : "border-black/10 bg-white text-black/35"}`}>{active ? <CheckCircle2 className="h-3.5 w-3.5"/> : <MinusCircle className="h-3.5 w-3.5"/>}{name}</div>; }

function ManualNotesSection() { return <div className="print-avoid-break"><Section title="Office Notes & Manual Proceeding Remarks"><div className="border border-[#1E3E62]/40 bg-white p-3 print:p-2 space-y-3 font-mono"><div><div className="mb-1 flex items-center justify-between text-[8px] font-bold uppercase tracking-widest text-[#3A506B]"><span>1. Hearing / Court Proceedings & Orders</span><span>Date: _________________</span></div><div className="space-y-4 pt-1"><div className="h-4 border-b border-dashed border-[#1E3E62]/30"/><div className="h-4 border-b border-dashed border-[#1E3E62]/30"/><div className="h-4 border-b border-dashed border-[#1E3E62]/30"/></div></div><div className="grid grid-cols-1 gap-3 border-t border-[#1E3E62]/15 pt-2 sm:grid-cols-2"><div><div className="mb-1 text-[8px] font-bold uppercase tracking-widest text-[#3A506B]">2. Action Required / Follow-up Steps</div><div className="space-y-4 pt-1"><div className="h-4 border-b border-dashed border-[#1E3E62]/30"/><div className="h-4 border-b border-dashed border-[#1E3E62]/30"/></div></div><div className="flex flex-col justify-between"><div className="mb-1 text-[8px] font-bold uppercase tracking-widest text-[#3A506B]">3. Counsel / Officer Signature & Stamp</div><div className="flex items-end justify-between gap-2 pt-2"><div className="space-y-1 text-[8px] text-[#3A506B]"><div>Sign: ___________________</div><div>Date: ___________________</div></div><div className="flex h-12 w-28 items-center justify-center rounded border-2 border-dashed border-[#1E3E62]/30 p-1 text-center text-[7px] font-bold uppercase tracking-wider text-[#3A506B]">Official Stamp Box</div></div></div></div></div></Section></div>; }

function ImageSection({ record }: { record: TrademarkRecord }) { const [open,setOpen]=useState(false); if(!record.image) return null; const img=record.image; return <Section title="Trademark / Mark Image"><div className="flex items-start gap-4"><button onClick={()=>setOpen(true)} className="flex h-32 w-32 shrink-0 items-center justify-center overflow-hidden border-2 border-[#1E3E62] bg-white hover:border-[#C94A00]"><img src={img} alt={record.appName} className="h-full w-full object-contain p-1"/></button><div className="font-mono text-xs"><div className="text-[8px] font-bold uppercase tracking-widest text-[#3A506B]">Mark / Application</div><div className="font-bold text-[#0A1931]">{record.appName}</div><div className="mt-1 text-[#3A506B]">TM / CPR: {record.tmCprNo || ""}</div><div className="text-[#3A506B]">Class: {record.appClass || ""}</div>{img.startsWith("http")&&<a href={img} target="_blank" rel="noreferrer" className="mt-2 flex items-center gap-1 font-bold text-[#C94A00] print:hidden"><ExternalLink className="h-3 w-3"/> Open source</a>}</div></div>{open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4 print:hidden" onClick={()=>setOpen(false)}><div className="max-h-[92vh] max-w-5xl overflow-auto border-4 border-white bg-white p-2" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between bg-black px-3 py-2 text-white"><span className="font-mono text-[10px] font-black">{record.appName} · TM {record.tmCprNo}</span><button onClick={()=>setOpen(false)}><X className="h-4 w-4"/></button></div><img src={img} alt={record.appName} className="mx-auto max-h-[84vh] w-auto object-contain"/></div></div>}</Section>; }

function DocumentControl({ record, id }: { record: TrademarkRecord; id: string }) {
  const qc=useQueryClient(); const [journalNo,setJournalNo]=useState(record.journalNumber||""); const [journalDate,setJournalDate]=useState(record.journalDate?String(record.journalDate).slice(0,10):""); const [saved,setSaved]=useState(false);
  const save=useMutation({mutationFn:async(patch:Record<string,unknown>)=>{const {error}=await supabase.from("trademarks").update(patch).eq("id",id);if(error)throw error;},onSuccess:()=>{qc.invalidateQueries({queryKey:["record",id]});qc.invalidateQueries({queryKey:["trademarks"]});setSaved(true);setTimeout(()=>setSaved(false),1200);}});
  const toggle=(key:DocKey)=>save.mutate({[key]:!Boolean(record[key])});
  const oppositionReceived=/OPPO.*RECEIVED|OPPOSITION.*RECEIVED/i.test(record.subStage||"");
  const base=new Date(record.updatedAt||record.date||new Date().toISOString()); const due=new Date(base); due.setMonth(due.getMonth()+1);
  return <Section title="TM Document Control"><div className="grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-3">{DOCS.map(d=><button key={d.key} disabled={save.isPending} onClick={()=>toggle(d.key)} className={`text-left border-2 p-3 ${record[d.key]?"border-[#0A6B52] bg-[#0D9970]/10":"border-black/10 bg-white"}`}><div className="flex items-center gap-2">{record[d.key]?<CheckCircle2 className="h-4 w-4 text-[#0A6B52]"/>:<MinusCircle className="h-4 w-4 text-black/30"/>}<span className="font-mono text-sm font-black">{d.code}</span><span className="font-mono text-[9px] font-bold uppercase">{d.title}</span></div><div className="mt-1 pl-6 font-mono text-[9px] leading-tight text-[#6d6658]">{d.detail}</div></button>)}</div>{oppositionReceived&&<div className="mt-3 border-2 border-[#C94A00] bg-[#C94A00]/5 p-3 font-mono text-xs"><b>⚠ OPPOSITION RECEIVED — ONE-MONTH REPLY WINDOW</b><div className="mt-1">Counter-statement / reply should be filed within one month. Current calculated deadline: <b>{formatDateShort(due.toISOString())}</b>.</div></div>}<div className="mt-4 border-2 border-[#1E3E62]/20 bg-white p-3"><div className="mb-3 flex items-center gap-2"><BookOpen className="h-4 w-4 text-[#0A6B52]"/><span className="font-mono text-xs font-black uppercase tracking-widest">Journal Record</span></div><div className="grid grid-cols-1 gap-3 sm:grid-cols-3"><label className="font-mono text-[9px] font-bold uppercase">Journal No<input value={journalNo} onChange={e=>setJournalNo(e.target.value)} className="mt-1 h-9 w-full border-2 border-black px-2 font-mono text-xs"/></label><label className="font-mono text-[9px] font-bold uppercase">Publication Date<input type="date" value={journalDate} onChange={e=>setJournalDate(e.target.value)} className="mt-1 h-9 w-full border-2 border-black px-2 font-mono text-xs"/></label><div className="flex items-end"><button type="button" onClick={()=>save.mutate({journal_number:journalNo||null,journal_date:journalDate||null})} className="flex h-9 items-center gap-2 bg-[#0A1931] px-3 font-mono text-[10px] font-bold uppercase text-white"><Save className="h-3.5 w-3.5"/>{saved?"SAVED":"SAVE JOURNAL"}</button></div></div></div></Section>;
}

export function RecordView({ params }: Props) {
  const {id}=params; const [,navigate]=useLocation(); const [editOpen,setEditOpen]=useState(false); const [imageOpen,setImageOpen]=useState(false); const qc=useQueryClient();
  const {data:record,isLoading,error,refetch}=useQuery<TrademarkRecord|null>({queryKey:["record",id],queryFn:()=>getRecord(id),staleTime:30_000,retry:1});
  if(isLoading)return <AppShell><div className="flex h-full items-center justify-center bg-[#F0E8D0] font-mono text-xs font-black uppercase tracking-widest animate-pulse">Loading secure case record…</div></AppShell>;
  if(error||!record)return <AppShell><div className="flex h-full flex-col items-center justify-center bg-[#F0E8D0] p-8 text-center"><h1 className="font-serif text-2xl uppercase">Record not found</h1><button onClick={()=>navigate("/database")} className="mt-4 bg-[#0C0C0C] px-4 py-2 font-mono text-xs font-black text-white">BACK TO DATABASE</button></div></AppShell>;
  const compromised=record.condition&&record.condition!=="NORMAL"; const stageColor=STATUS_COLOR[record.stage]??"bg-[#E8DFC7] text-black";
  const saved=()=>{setEditOpen(false);qc.invalidateQueries({queryKey:["record",id]});qc.invalidateQueries({queryKey:["trademarks"]});qc.invalidateQueries({queryKey:["stats"]});refetch();};
  return <AppShell><div className="flex h-full min-h-0 flex-col bg-[#F0E8D0]"><header className="shrink-0 border-b-2 border-black bg-[#0C0C0C] px-4 py-3 text-white print:hidden"><div className="flex flex-wrap items-center gap-2"><button onClick={()=>navigate("/database")} className="flex items-center gap-1.5 px-2 py-1.5 font-mono text-[10px] font-black uppercase"><ArrowLeft className="h-4 w-4"/> Database</button><div className="ml-auto flex gap-2"><button onClick={()=>setEditOpen(true)} className="flex items-center gap-1.5 bg-[#C94A00] px-3 py-1.5 font-mono text-[10px] font-black"><Edit2 className="h-3.5 w-3.5"/> Edit</button><button onClick={()=>window.print()} className="flex items-center gap-1.5 bg-white px-3 py-1.5 font-mono text-[10px] font-black text-black"><Printer className="h-3.5 w-3.5"/> Print</button></div></div></header>
  <main className="min-h-0 flex-1 overflow-auto"><div className="mx-auto max-w-6xl space-y-6 bg-white p-4 sm:p-6 print:p-5"><div className={`border-2 border-black p-4 sm:p-6 ${compromised?"bg-red-50":"bg-white"}`}><div className="mb-4 hidden items-center gap-3 border-b-2 border-[#0A1931] pb-3 print:flex"><img src="/brandex-logo.png" alt="Brandex Law Associates" className="h-11 w-11 object-contain"/><div><div className="font-serif text-xl font-bold tracking-wider text-[#0A1931]">BRANDEX LAW ASSOCIATES</div><div className="font-mono text-[8px] font-bold uppercase tracking-[0.2em] text-[#C94A00]">Trademark & IP Registry · Case Record</div></div></div><div className="flex flex-col gap-5 lg:flex-row"><div className="flex min-h-[210px] w-full items-center justify-center border-2 border-black/15 bg-[#F8F6EF] p-3 lg:w-[260px] lg:shrink-0">{record.image?<button onClick={()=>setImageOpen(true)} className="h-full w-full cursor-zoom-in"><img src={record.image} alt={record.appName} className="mx-auto max-h-[240px] w-full object-contain"/></button>:<div className="text-center font-mono text-[9px] font-black uppercase text-black/30"><ImageIcon className="mx-auto mb-2 h-7 w-7"/>No mark image</div>}</div><div className="min-w-0 flex-1"><div className="font-mono text-[9px] font-black uppercase tracking-widest text-[#6d6658]">{record.prefix||record.type||"—"} · CLIENT {record.clientCode||"—"} · CASE {record.caseNumber||"—"}</div><h1 className="mt-2 font-serif text-3xl uppercase leading-tight tracking-wide sm:text-4xl">{record.appName||"Untitled Mark"}</h1><div className="mt-2 font-mono text-lg font-black text-[#0A6B52]">TM / CPR {record.tmCprNo||"—"}</div><div className="mt-6 grid grid-cols-2 gap-4 border-t-2 border-black/10 pt-4 sm:grid-cols-4"><Field label="Filing Date" value={formatDateShort(record.date)}/><Field label="Last Modified" value={formatDate(record.updatedAt)}/><Field label="Class" value={record.appClass}/><Field label="City" value={record.city}/></div></div><div className="flex shrink-0 flex-col items-start gap-2 lg:items-end"><span className={`px-3 py-1.5 font-mono text-[10px] font-black uppercase ${stageColor}`}>{record.stage||"NO STATUS"}</span><span className="max-w-[240px] text-right font-mono text-xs font-black">{record.subStage||"No sub-status"}</span></div></div>{compromised&&<div className="mt-4 border-2 border-red-900/20 bg-red-100/60 px-3 py-2 font-mono text-[10px] font-black uppercase text-red-900">⚠ {record.condition} {record.isProlonged?"· PROLONGED CASE":"· SPECIAL ATTENTION"}</div>}</div>
  <Section title="Case Information"><div className="grid grid-cols-2 gap-x-5 gap-y-4 border-2 border-black/10 bg-white p-4 sm:grid-cols-4"><Field label="Prefix" value={record.prefix||record.type}/><Field label="Client Code" value={record.clientCode}/><Field label="Case / Folder Number" value={record.caseNumber}/><Field label="Case Type" value={record.caseType}/><Field label="Agent / Counsel" value={record.agent}/><Field label="City" value={record.city}/><Field label="Application / Mark" value={record.appName} wide/><Field label="TM / CPR Number" value={record.tmCprNo} wide/><Field label="Notes" value={record.notes} wide/></div></Section>
  <ImageSection record={record}/><DocumentControl record={record} id={id}/><RecordHistoryPanel trademarkId={record.id} tm11={record.tm11===true||record.tm11==="YES"}/>{record.journal&&<Section title="Journal Publication"><div className="border-2 border-[#0A6B52]/30 bg-white p-4"><div className="grid grid-cols-2 gap-4 sm:grid-cols-4"><Field label="Journal No" value={String(record.journal["Journal No"]||record.journalNumber||"")}/><Field label="Journal Date" value={String(record.journal["Journal Date"]||record.journalDate||"")}/><Field label="Application No" value={String(record.journal["Application No"]||"")}/><Field label="Class" value={String(record.journal["Class"]||record.appClass||"")}/></div><div className="mt-4"><Field label="Title" value={String(record.journal["Title"]||record.appName||"")} wide/></div></div></Section>}<ManualNotesSection/><footer className="border-t-2 border-[#0A1931] pt-2 text-center font-mono text-[7px] uppercase tracking-widest text-[#6d6658]">Brandex Law Associates · Confidential Office Record · {record.prefix||""} · {record.clientCode||""} · {record.caseNumber||""}</footer></div></main>
  {imageOpen&&record.image&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/85 p-4 print:hidden" onClick={()=>setImageOpen(false)}><div className="max-h-[92vh] max-w-5xl border-4 border-white bg-white p-2" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between bg-black px-3 py-2 text-white"><span className="font-mono text-[10px] font-black uppercase">{record.appName} · TM {record.tmCprNo}</span><button onClick={()=>setImageOpen(false)}>CLOSE ✕</button></div><img src={record.image} alt={record.appName} className="max-h-[82vh] w-auto object-contain"/></div></div>}{editOpen&&<RecordModal recordId={id} isNew={false} onClose={()=>setEditOpen(false)} onSaved={saved}/>}</div></AppShell>;
}
